# Generated by Django 2.0 on 2018-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180104_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_project', models.TextField(max_length=500)),
                ('learnings', models.TextField(max_length=1000)),
            ],
        ),
    ]
