# Generated by Django 2.0 on 2018-01-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
